$Env:DBHOST = "jobs4me-server"
$Env:DBUSER = "dean"
$Env:DBNAME = "jos4medb"
$Env:DBPASS = "Iotisfun2"
$Env:JOBS4ME_SMS_SERVICE = "endpoint=https://jobs4me-sms-service.communication.azure.com/;accesskey=XCSp5AKE1mnsH3mpbLaFXibjbC35mda2YOsNPu+oTahmpXYk22jUUzH2aEvyDhdsr5Qv8qU6R/Pe5yZM6UYr7A=="