# Generated by Django 3.1.6 on 2021-12-04 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs4me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='Phone number was entered incorrectly! Make sure it is E.164 international standard format (e.g.: +14255550123)', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
