# Generated by Django 3.1.6 on 2021-11-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs4me', '0002_auto_20211128_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
