# Generated by Django 3.1.6 on 2021-11-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs4me', '0003_auto_20211128_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
